version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install the Dependencies
          command: |
            pip install -r requirements.txt # In this file I am keeping all the dependencies required (numpy, scipy ..)
      - run: 
          name: Testing the Test cases
          command: |
            pytest test_sparse_recommender.py
      - run: 
          name: Build Docker image
          command: |
            docker build -t sandeepreddiee/psd-docker-assignment:latest .
      - run:
          name: Push to Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push sandeepreddiee/psd-docker-assignment:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test